// Pages and static files: the quest board, the message board, dispatch history, and review pages.
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { sendFile, sendJson, safeJoin } from './http.js';

const PUBLIC = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..', 'public');
// The quest board runs only its own script file; the one outside origin is Google Fonts (with fallbacks).
const BOARD_CSP = "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self'";
// The message board and history pages still carry inline scripts (to be restyled with the board).
const INLINE_CSP = "default-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline'";
// Review pages are generated by agents: they may save annotations and nothing else from this origin.
const REVIEW_CSP = "default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; connect-src http://127.0.0.1:*/api/annotations http://localhost:*/api/annotations";
const ASSETS = new Set(['quests.css', 'quests.app.js']);
const PAGES = {
  '/': ['quests.html', BOARD_CSP],
  '/dashboard': ['quests.html', BOARD_CSP],
  '/board': ['board.html', INLINE_CSP],
  '/history': ['history.html', INLINE_CSP],
  '/lanes': ['history.html', INLINE_CSP],
};

export function createPageRoutes({ config }) {
  async function handle(request, response, url, parts) {
    if (request.method !== 'GET') return false;
    const page = PAGES[url.pathname];
    if (page) { sendFile(response, path.join(PUBLIC, page[0]), { csp: page[1] }); return true; }
    if (parts[0] === 'assets') {
      if (parts.length === 2 && ASSETS.has(parts[1])) sendFile(response, path.join(PUBLIC, parts[1]));
      else sendJson(response, 404, { error: 'not found' });
      return true;
    }
    if (parts[0] === 'review') {
      if (!config.reviewPages) { sendJson(response, 404, { error: 'this project has no review pages' }); return true; }
      const file = safeJoin(config.reviewPages.dir, parts.slice(1).join('/'));
      sendFile(response, file, { csp: file && file.endsWith('.html') ? REVIEW_CSP : undefined });
      return true;
    }
    return false;
  }
  return { handle };
}
